# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: realist
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: realist
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DEBUG: ${env:DEBUG, 0}
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
